### ISSUE TITLE
I can not update my post

### ISSUE THREAD

**Issue by erichuang2015** [blyamur/Montgo#1]
Hello

I can not update my post by using this theme

It shows errors as below

http://localhost/wp-json/wp/v2/media?_locale=user 404 (Not Found)

it is this file http://localhost/wp-includes/js/dist/api-fetch.min.js?ver=3.1.2 throws out this error

When I switch back to other themes it is ok

**Comment by blyamur** [comment]
Download the updated version of the theme. Or, delete lines between 31 and 53 in the functions.php file.

I checked on the latest version, I was able to repeat the error you are writing about. She is associated with the new editor and permalinks. On the version that I use, it is all off, so the error slipped by. Now I made some changes to functions.php and checked that my error went away. Try it, let me know about the result.

**Comment by erichuang2015** [comment]
Hello

new errors

FATAL ERROR: UNCAUGHT ERROR: CALL TO UNDEFINED FUNCTION GETPOSTVIEWS()

**Comment by blyamur** [comment]
Try downloading the updated functions.php file .  (I apparently accidentally deleted the function used). Below I give a code that can replace the entire contents of the functions.php file

Please write about the result

**Comment by blyamur** [comment]
Problem resolved
